# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('clueid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cluenumber', models.IntegerField()),
                ('cluetext', models.CharField(max_length=200)),
                ('clue_image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locationid', models.BigAutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MyAdventures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='adventures',
            name='id',
        ),
        migrations.AddField(
            model_name='adventures',
            name='adventureid',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventures',
            name='difficulty',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myadventures',
            name='adventureid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventures'),
        ),
        migrations.AddField(
            model_name='myadventures',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.User'),
        ),
        migrations.AddField(
            model_name='clues',
            name='adventureid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventures'),
        ),
        migrations.AddField(
            model_name='clues',
            name='locationsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Locations'),
        ),
    ]
