# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_auto_20170928_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='adventureid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure', to='adventures.Adventures'),
        ),
    ]
