# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_auto_20171001_0804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adventures',
            new_name='Adventure',
        ),
        migrations.RenameModel(
            old_name='Clues',
            new_name='Clue',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='MyAdventures',
            new_name='MyAdventure',
        ),
    ]
