# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_auto_20171001_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myadventure',
            name='adventureid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventure', unique=True),
        ),
    ]
